### ISSUE TITLE
Convert this resources into github pages

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Ultimate-NodeJs-Resources#15]

**Comment by sahalhes** [comment]
@DhanushNehru Hey can you please assign me this issue after elaborating a bit what is to be converted into which file format etc

**Comment by DhanushNehru** [comment]
We have a lot of resources in this repository, you can try converting it to a github page where people can easily navigate and access things @sahalhes

**Comment by sahalhes** [comment]
@DhanushNehru Hey I have done PR, please review it and tell if there are any changes required.

**Comment by DhanushNehru** [comment]
https://dhanushnehru.github.io/Ultimate-NodeJs-Resources/
