### ISSUE TITLE
Want to Add Hindi Youtube Channels in Readme file and Want Blog Related to NodeJS Architecture

### ISSUE THREAD

**Issue by Adidem23** [DhanushNehru/Ultimate-NodeJs-Resources#16]
Besides this , There are also many  topics in which nodeJS plays Important Role Such as 
- NGINX Server
- Kafka
- Grafana
-

**Comment by DhanushNehru** [comment]
Blog related to NODE JS is fine , but can we stick with English youtube channels as it would benefit globally ? @Adidem23

**Comment by Adidem23** [comment]
Okay . I wil try descriptive blog related to node js architecture along with scalability and what do you think about these complementary topics NGINX server , Docker , kubernetes and Kafka

**Comment by DhanushNehru** [comment]
The complementary topics you can contribute in this repo https://github.com/DhanushNehru/Ultimate-DevOps-Resources @Adidem23

**Comment by Adidem23** [comment]
Okay Thank you 😊

**Comment by Adidem23** [comment]
Should I add popular blogs or my own blog in pr .

**Comment by DhanushNehru** [comment]
Popular blogs only @Adidem23

**Comment by Adidem23** [comment]
Ok , I will add hashnode blogs and node js architecture blogs and points on tutorialspoint
